config/routes.rb
Rails.application.routes.draw do
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :todos
  resources :users

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'welcome', to: 'sessions#welcome'
  delete 'logout', to: 'sessions#destroy'

  get 'authorized', to: 'sessions#page_requires_login'

  root to: 'sessions#welcome'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  has_many :user_todos
  has_many :users, through: :user_todos

  scope :completed_todos, -> { where(complete: true)}


  # def self.completed_todos
  #   self.all.select{ | todo | todo.complete == true }
  # end

  # def self.completed_todos
  #   where(complete:true)
  # end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_todos
  has_many :todos, through: :user_todos

  has_secure_password

  validates :username, presence: true, uniqueness: true
end

app/models/user_todo.rb
class UserTodo < ApplicationRecord
  belongs_to :user
  belongs_to :todo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authorized
  helper_method :current_user
  helper_method :logged_in?

  def current_user
    @user ||= User.find_by_id(session[:user_id])
  end


  def logged_in?
    !current_user.nil?
  end

  def authorized
    redirect_to '/welcome' unless logged_in?
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authorized, only: [:new, :create, :welcome]

  def new
  end

  def login
  end

  def page_requires_login
  end

  def create
    @user = User.find_by(username: params[:username])
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      redirect_to 'login'
    end
  end

  def destroy
    session.clear
    redirect_to '/welcome'
  end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController

  

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authorized, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to '/welcome'
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_nav.erb
<% if !logged_in? %>
<ul>
  <li><%= link_to 'Log in', login_path %></li>
  <li> <%= link_to 'Sign up', new_user_path %></li>
  <% else %>
    <li><%= link_to 'Log out', logout_path, method: :delete %></li>
</ul>
<% end %>

<% if logged_in? %>
  <h2>Nice to see you, <%= current_user.username %>!</h2>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NativeAuthApplication</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <%= yield %>
  </body>
</html>

app/views/users/new.erb
<% if @user.errors.any? %>
  <%= @user.errors.full_messages.to_sentence %>
<% end %>


<h1>Would you like to sign up?</h1>

<%= form_with model: @user, local: true do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %><br />

  <%= f.label :password %>
  <%= f.password_field :password %><br />

  <%= f.submit "Sign up" %>
<% end %>